name: Hello Scan
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL der zu scannenden Seite'
        required: true
        default: 'https://www.w3.org/WAI/demos/bad/'

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run hello scan
        run: npm run hello-scan -- --url="${{ github.event.inputs.url }}" --out=out
      - name: Archive reports
        uses: actions/upload-artifact@v4
        with:
          name: accesschecker-reports
          path: backend/out/*
