name: Site Scan

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Start-URL'
        required: true
        default: 'https://www.w3.org/WAI/demos/bad/'
      max_pages:
        description: 'Max. Seiten'
        required: false
        default: '200'
      max_depth:
        description: 'Max. Tiefe'
        required: false
        default: '10'
      scope:
        description: 'Crawl-Scope (same-origin|same-site|domain-list)'
        required: false
        default: 'same-origin'
      domain_allowlist:
        description: 'Allowlist-Domains (Komma-getrennt)'
        required: false
        default: ''
      seed_sitemap:
        description: 'sitemap.xml als Seed nutzen'
        required: false
        default: 'true'
      respect_robots:
        description: 'robots.txt Modus (respect|audit|ignore)'
        required: false
        default: 'respect'
      respect_hash_routes:
        description: 'Hash-Routen (#/...) als eigene Seiten'
        required: false
        default: 'true'
      click_consent:
        description: 'Consent-Banner (auto|none|custom)'
        required: false
        default: 'auto'
      extra_config_json:
        description: 'Zusätzliche Konfiguration als JSON (Keys = Env-Variablen)'
        required: false
        default: '{}'

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 75
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install --no-audit --no-fund
        working-directory: backend

      - name: Install Playwright (browsers + deps)
        run: npx playwright install --with-deps
        working-directory: backend

      - name: Set default config
        run: |
          cat <<'EOCONF' >> $GITHUB_ENV
          CHECK_IFRAMES=true
          CUSTOM_CONSENT_SELECTORS=
          DYNAMIC_INTERACTIONS=true
          WAIT_STRATEGY=networkidle
          WAIT_SELECTOR=
          WAIT_MS=0
          RATE_LIMIT_DELAY_MS_MIN=200
          RATE_LIMIT_DELAY_MS_MAX=600
          NAVIGATION_TIMEOUT_MS=45000
          ACTION_TIMEOUT_MS=45000
          USER_AGENT=
          VIEWPORT_WIDTH=1200
          VIEWPORT_HEIGHT=800
          DOWNLOADS_ENABLED=true
          DOWNLOADS_TYPES=pdf,docx,pptx,doc,ppt
          DOWNLOADS_MAX_BYTES=5242880
          LINK_FILTERS_INCLUDE=
          LINK_FILTERS_EXCLUDE=
          EOCONF

      - name: Apply extra config
        if: ${{ github.event.inputs.extra_config_json != '{}' }}
        run: |
          echo "${{ github.event.inputs.extra_config_json }}" | jq -r 'to_entries|.[]|"\(.key)=\(.value)"' >> $GITHUB_ENV
        shell: bash

      - name: Run crawl
        run: npm run crawl -- --url ${{ github.event.inputs.url }} --max-pages ${{ github.event.inputs.max_pages }} --max-depth ${{ github.event.inputs.max_depth }} --scope ${{ github.event.inputs.scope }} --domain-allowlist "${{ github.event.inputs.domain_allowlist }}" --seed-sitemap ${{ github.event.inputs.seed_sitemap }} --respect-robots ${{ github.event.inputs.respect_robots }} --respect-hash-routes ${{ github.event.inputs.respect_hash_routes }} --click-consent ${{ github.event.inputs.click_consent }}
        working-directory: backend

      - name: Build reports
        run: npm run build:reports
        working-directory: backend

      - name: Audit Norm References
        run: npm run lint:norms
        working-directory: backend

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: accesschecker-site-scan
          path: backend/out/**
