name: Site Scan

on:
  workflow_dispatch:
    inputs:
      start_url:
        description: 'Start-URL für den Scan'
        required: true
        default: 'https://example.com'
      max_pages:
        description: 'Maximale Anzahl zu crawlender Seiten'
        required: false
        default: '50'
      check_downloads:
        description: 'Downloads (PDF/DOCX/PPTX) prüfen'
        required: false
        default: 'true'

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Install Playwright
        run: npx playwright install --with-deps
        working-directory: backend

      - name: Run crawl-scan
        run: |
          START_URL=${{ github.event.inputs.start_url }} \
          MAX_PAGES=${{ github.event.inputs.max_pages }} \
          CHECK_DOWNLOADS=${{ github.event.inputs.check_downloads }} \
          npm run crawl-scan
        working-directory: backend

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: accesschecker-site-scan
          path: backend/out
