name: Site Scan

on:
  workflow_dispatch:
    inputs:
      start_url:
        description: 'Start-URL'
        required: true
        default: 'https://www.w3.org/WAI/demos/bad/'
      max_pages:
        description: 'Max. Seiten'
        required: false
        default: '50'
      max_depth:
        description: 'Max. Tiefe'
        required: false
        default: '3'
      respect_robots:
        description: 'robots.txt respektieren (true/false)'
        required: false
        default: 'true'
      seed_sitemap:
        description: 'sitemap.xml als Seed nutzen (true/false)'
        required: false
        default: 'true'
      respect_hash_routes:
        description: 'Hash-Routen (#/...) als eigene Seiten behandeln'
        required: false
        default: 'true'
      check_iframes:
        description: 'iframes (same-origin) zusätzlich scannen'
        required: false
        default: 'true'
      consent_click:
        description: 'Consent-Buttons (Cookie-Banner) klicken'
        required: false
        default: 'true'
      check_downloads:
        description: 'Downloads (PDF/DOCX/PPTX) prüfen'
        required: false
        default: 'true'

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 75

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm install --no-audit --no-fund
        working-directory: backend

      - name: Install Playwright (browsers + deps)
        run: npx playwright install --with-deps
        working-directory: backend

      - name: Run crawl-scan (tsx)
        timeout-minutes: 20
        env:
          START_URL: ${{ github.event.inputs.start_url }}
          MAX_PAGES: ${{ github.event.inputs.max_pages }}
          MAX_DEPTH: ${{ github.event.inputs.max_depth }}
          RESPECT_ROBOTS: ${{ github.event.inputs.respect_robots }}
          SEED_SITEMAP: ${{ github.event.inputs.seed_sitemap }}
          RESPECT_HASH_ROUTES: ${{ github.event.inputs.respect_hash_routes }}
          CHECK_IFRAMES: ${{ github.event.inputs.check_iframes }}
          CONSENT_CLICK: ${{ github.event.inputs.consent_click }}
          CHECK_DOWNLOADS: ${{ github.event.inputs.check_downloads }}
        run: |
          n=0
          until [ "$n" -ge 2 ]
          do
            n=$((n+1))
            npx tsx scripts/crawl-scan.ts && break
            echo "retrying crawl ($n)"
            sleep 5
          done
        working-directory: backend

      - name: Render PDF reports
        run: npx tsx scripts/build-reports.ts
        working-directory: backend

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: accesschecker-site-scan
          path: |
            backend/out/*.json
            backend/out/report_internal.html
            backend/out/report_public.html
            backend/out/report_public.pdf
