name: Site Scan

on:
  workflow_dispatch:
    inputs:
      start_url:
        description: 'Start-URL für den Scan'
        required: true
        default: 'https://www.w3.org/WAI/demos/bad/'
      max_pages:
        description: 'Maximale Anzahl zu crawlender Seiten'
        required: false
        default: '50'
      check_downloads:
        description: 'Downloads (PDF/DOCX/PPTX) prüfen'
        required: false
        default: 'true'

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --no-audit --no-fund
        working-directory: backend

      - name: Install Playwright (browsers + deps)
        run: npx playwright install --with-deps
        working-directory: backend

      - name: Run crawl-scan (via tsx)
        run: |
          export START_URL="${{ github.event.inputs.start_url }}"
          export MAX_PAGES="${{ github.event.inputs.max_pages }}"
          export CHECK_DOWNLOADS="${{ github.event.inputs.check_downloads }}"
          npx tsx scripts/crawl-scan.ts
        working-directory: backend

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: accesschecker-site-scan
          path: backend/out
